web:
  build: ./nodejs/
  ports:
    - "5000:5000"
  volumes:
    - "./nodejs:/src/app"

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/public
  volumes_from:
    - web
  links:
    - web:web
