version: '3.7'

services:

  # Web
  web:
    build: ./nodejs/
    ports:
      - "5000:5000"
    volumes:
      - "./nodejs:/src/app"

  # Nginx
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/public
    links:
      - web:web
