#
# Hello world Dockerfile
#
FROM scratch

# Maintainer details
MAINTAINER Adrian Novegil "adrian.novegil@gmail.com"

# Copu the hello program to the container.
COPY hello /

# Execute the program hello
CMD ["/hello"]
